services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://${bootstrap_server},CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${bootstrap_server}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    ports:
      - 9092:9092

    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --bootstrap-server ${bootstrap_server} --list
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  raw_producer:
    build:
      context: ./RawProducer
      dockerfile: Dockerfile
    container_name: raw_producer
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - bootstrap_server=${bootstrap_server}
      - raw_topic_name=${raw_topic_name}
      - client_id=${raw_producer_client_id}
